version: '3'

volumes:
  jenkins_home:
  jenkinsRef:

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - 80:8080
    #container_name: jenkins-controller
    volumes:
      - jenkins_home:/var/jenkins_home
      - "/home/opc/private:/var/jenkins_home/private"
      - jenkinsRef:/usr/share/jenkins/ref
      - "/home/opc/casc.yaml:/jenkins/config/casc.yaml"
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - JENKINS_AGENT_SSH_PRIVKEY=/var/jenkins_home/private
      - JENKINS_ADMIN_ID=${jenkins_user}
      - JENKINS_ADMIN_PASSWORD=${jenkins_password}
      - CASC_JENKINS_CONFIG=/jenkins/config/casc.yaml

  agent:
    # java path /opt/java/openjdk/bin/java for agent configuration
    image: jenkins/ssh-agent:jdk11
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
      - "/home/opc/.ssh/authorized_keys:/home/jenkins/.ssh/authorized_keys"
    # add the below if you want to use root user
    #privileged: true
    #user: root
    #container_name: jenkins-agent
    expose:
      - 22
    environment:
      # add the ssh-pub-key for ssh connection between controller/agent
      - JENKINS_AGENT_SSH_PUBKEY=/home/jenkins/.ssh/authorized_keys