version: '3'

volumes:
  jenkins_home:
  jenkinsRef:

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - 80:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkinsRef:/usr/share/jenkins/ref
      - "/home/opc/casc.yaml:/jenkins/config/casc.yaml"
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - JENKINS_ADMIN_ID=${jenkins_user}
      - JENKINS_ADMIN_PASSWORD=${jenkins_password}
      - CASC_JENKINS_CONFIG=/jenkins/config/casc.yaml
      
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: jenkins-agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu+ChycaZixWijyjw4A1N9qm/Mmfb/QtcItSkNDWvOXJVGkwvOu3qjhSpVQvH/eeJq/MIZNggOnkJr/G5W8vAjtf9phHV4aXt3DEPH5y5EXAJ7opmVc/Y5fUwa27vHzntQpoAv0UfCJQLvIrMkJDT8qK4cSlxIsEgvYOCpy7J/rQ2UuZ+yhdgxTUDAK94FDkLKXHVcEGKBnYNz9L9Rtw9b35riHA460387NUyRY3th3tTqW7ukub2q3BbwoDRekc7mgzBFLaZZ+0nzfdiad6SgTuzWXWUKA1S9dLFSDDTNSSklTqRzbMf0FZpCPrS/HrXMEgD+sK/KEj2MlEdy+FW5 ssh-key-2023-01-19